---
abstract: 'manipulation of UTC in terms of TAI'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  Math::BigRat: 0.04
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.006
  strict: 0
  warnings: 0
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-UTC
provides:
  Time::UTC:
    file: lib/Time/UTC.pm
    version: 0.007
  Time::UTC::Segment:
    file: lib/Time/UTC/Segment.pm
    version: 0.007
requires:
  Carp: 0
  Digest::SHA1: 0
  Exporter: 0
  LWP: 5.5394
  LWP::UserAgent: 0
  Math::BigRat: 0.13
  Time::Unix: 1.02
  constant: 0
  integer: 0
  parent: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.007
