# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Time-UTC
version:      0.001
version_from: lib/Time/UTC.pm
installdirs:  site
requires:
    LWP:                           5.53_94
    LWP::UserAgent:                
    Math::BigRat:                  0.08
    Time::Unix:                    1.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
