---
name: Time-UTC
version: 0.004
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
abstract: manipulation of UTC in terms of TAI
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Exporter: 0
  LWP: 5.5394
  LWP::UserAgent: 0
  Math::BigRat: 0.08
  Time::Unix: 1.02
  base: 0
  constant: 0
  integer: 0
  perl: 5.006
  strict: 0
  warnings: 0
build_requires:
  Math::BigRat: 0.04
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
dynamic_config: 0
provides:
  Time::UTC:
    file: lib/Time/UTC.pm
    version: 0.004
  Time::UTC::Segment:
    file: lib/Time/UTC/Segment.pm
    version: 0.004
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: module
